# Generated by Django 5.0.3 on 2024-04-02 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_title'),
        ('user', '0002_user_delete_usuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='like_post',
            new_name='Like',
        ),
    ]
