# Generated by Django 5.0.3 on 2024-04-05 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_like_user_alter_like_comment_user_and_more'),
        ('user', '0002_user_delete_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
